name: Swift

on:
  push:
    branches: [ master ]
    paths:
      - 'Sources/**/*'
      - 'Tests/**/*'
  pull_request:
    branches: [ master ]
    paths:
      - 'Sources/**/*'
      - 'Tests/**/*'

jobs:
  build:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test --enable-code-coverage -v
    - name: Convert to standart format
      run: |
        xcrun llvm-cov export -format="lcov" .build/debug/SolanaSwiftMagicPackageTests.xctest/Contents/MacOS/SolanaSwiftMagicPackageTests -instr-profile .build/debug/codecov/default.profdata > info.lcov

    - uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./info.lcov # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
